name: fcrec
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.10
  - python=3.11.4
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - absl-py==1.4.0
    - ace-tools==0.0
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - altair==5.4.1
    - annotated-types==0.7.0
    - anyio==4.6.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - argparse==1.4.0
    - arrow==1.3.0
    - asttokens==2.2.1
    - async-lru==2.0.4
    - attrs==23.2.0
    - autopep8==2.3.1
    - babel==2.16.0
    - backcall==0.2.0
    - backports-functools-lru-cache==1.6.6
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - blessed==1.20.0
    - bottleneck==1.3.7
    - brotlipy==0.7.0
    - cachetools==5.3.0
    - certifi==2022.12.7
    - cffi==1.15.1
    - charset-normalizer==3.2.0
    - click==8.1.8
    - cmake==3.27.2
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - comm==0.1.4
    - contourpy==1.1.0
    - cryptography==41.0.3
    - cycler==0.11.0
    - debugpy==1.6.7.post1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dgl==2.1.0
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - executing==1.2.0
    - fastjsonschema==2.20.0
    - filelock==3.12.2
    - flit-core==3.9.0
    - fonttools==4.25.0
    - fqdn==1.5.1
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - google-auth==2.16.1
    - google-auth-oauthlib==0.4.6
    - gpustat==1.1
    - grpcio==1.51.3
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.2
    - huggingface-hub==0.27.1
    - humanfriendly==10.0
    - idna==3.4
    - ipykernel==6.29.5
    - ipython==8.14.0
    - ipywidgets==8.1.5
    - iso3166==2.1.1
    - isoduration==20.11.0
    - jedi==0.19.0
    - jinja2==3.1.2
    - joblib==1.3.2
    - json5==0.9.25
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.3
    - jupyter-core==5.8.1
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.2
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.4.3
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.13
    - kiwisolver==1.4.4
    - lightning==2.5.1
    - lightning-utilities==0.14.1
    - lit==16.0.6
    - lux==0.5.1
    - lux-api==0.5.1
    - lux-widget==0.1.11
    - markdown==3.4.1
    - markupsafe==2.1.3
    - matplotlib==3.7.2
    - matplotlib-inline==0.1.6
    - mistune==3.0.2
    - mpmath==1.3.0
    - multidict==6.0.5
    - munkres==1.1.4
    - narwhals==1.8.4
    - nbclient==0.10.0
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.5.7
    - networkx==3.1
    - notebook==7.4.3
    - notebook-shim==0.2.4
    - numexpr==2.8.5
    - numpy==1.25.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-ml-py==12.535.77
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.4.127
    - oauthlib==3.2.2
    - overrides==7.7.0
    - packaging==23.1
    - pandas==1.5.2
    - pandocfilters==1.5.1
    - parso==0.8.3
    - pexpect==4.8.0
    - phe==1.5.0
    - pickleshare==0.7.5
    - pillow==9.3.0
    - pip==25.1.1
    - platformdirs==3.10.0
    - ply==3.11
    - prometheus-client==0.21.0
    - prompt-toolkit==3.0.39
    - protobuf==4.22.0
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.12.1
    - pycparser==2.21
    - pydantic==2.11.3
    - pydantic-core==2.33.1
    - pygments==2.16.1
    - pyopenssl==23.2.0
    - pyparsing==3.0.9
    - pyqt5-sip==12.11.0
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytorch-lightning==2.5.1
    - pytz==2023.3
    - pyyaml==6.0.2
    - pyzmq==26.4.0
    - rdkit==2023.9.5
    - recsys-metrics==0.0.4
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.20.0
    - rsa==4.9
    - safetensors==0.5.2
    - scikit-learn==1.3.0
    - scipy==1.11.2
    - seaborn==0.13.2
    - send2trash==1.8.3
    - sentence-transformers==3.3.1
    - sentencepiece==0.2.0
    - sentry-sdk==2.26.1
    - setproctitle==1.3.5
    - sh==2.0.7
    - simple-gpu-scheduler==0.1.4
    - sip==6.7.11
    - six==1.16.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - soupsieve==2.6
    - stack-data==0.6.2
    - sympy==1.13.1
    - tabulate==0.9.0
    - tensorboard==2.12.0
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6.2.2
    - terminado==0.18.1
    - threadpoolctl==3.2.0
    - tinycss2==1.2.1
    - tokenizers==0.21.0
    - toml==0.10.2
    - torch==2.6.0
    - torch-geometric==2.5.0
    - torchaudio==2.0.2
    - torchdata==0.7.1
    - torchmetrics==1.6.3
    - torchsummary==1.5.1
    - torchvision==0.15.2
    - tornado==6.5.1
    - tqdm==4.66.1
    - traitlets==5.14.3
    - transformers==4.48.0
    - triton==3.2.0
    - types-python-dateutil==2.9.0.20240906
    - typing-extensions==4.12.2
    - typing-inspection==0.4.0
    - uri-template==1.3.0
    - urllib3==2.0.4
    - wandb==0.19.9
    - wcwidth==0.2.6
    - webcolors==24.8.0
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - werkzeug==2.3.7
    - widgetsnbextension==4.0.13
    - yarl==1.9.4
